# Generated by Django 2.0.3 on 2018-04-17 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='gnr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genrealbum', to='mainapp.Genre'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userperformer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='gnr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genretrack', to='mainapp.Genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='link_trc',
            field=models.CharField(default='', max_length=50),
        ),
    ]
