# Generated by Django 2.0.3 on 2018-05-04 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='per_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='mainapp.Performer'),
        ),
        migrations.AlterField(
            model_name='album',
            name='stl_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='mainapp.GenreStyle'),
        ),
        migrations.AlterField(
            model_name='track',
            name='alb_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='mainapp.Album'),
        ),
        migrations.AddField(
            model_name='trackhistory',
            name='trc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackhistory', to='mainapp.Track'),
        ),
        migrations.AddField(
            model_name='trackhistory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userhistory', to=settings.AUTH_USER_MODEL),
        ),
    ]
