# Generated by Django 2.0.3 on 2018-05-20 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_auto_20180504_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackreport', to='mainapp.Track')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
