# Generated by Django 2.0.3 on 2018-05-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_trackreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackhistory',
            name='count',
        ),
    ]
