# Generated by Django 2.0.3 on 2018-06-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_trackhistory_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='per_id',
        ),
        migrations.RemoveField(
            model_name='album',
            name='stl_id',
        ),
        migrations.RemoveField(
            model_name='genrestyle',
            name='gnr_id',
        ),
        migrations.RemoveField(
            model_name='likedtrack',
            name='trc_id',
        ),
        migrations.RemoveField(
            model_name='likedtrack',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='track',
            name='alb_id',
        ),
        migrations.RemoveField(
            model_name='trackhistory',
            name='trc_id',
        ),
        migrations.RemoveField(
            model_name='trackhistory',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='trackreport',
            name='trc_id',
        ),
        migrations.RemoveField(
            model_name='trackreport',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='GenreStyle',
        ),
        migrations.DeleteModel(
            name='LikedTrack',
        ),
        migrations.DeleteModel(
            name='Performer',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.DeleteModel(
            name='TrackHistory',
        ),
        migrations.DeleteModel(
            name='TrackReport',
        ),
    ]
